"use client";
import type { Metadata } from "next";
import Header from "@/components/Hearder/Header";
import Footer from "@/components/Footer";
import Kart from "@/components/Kart/Kart";
import Alert from "@/components/Alert/Alert";
import { Provider } from "react-redux";
import { store } from "@/lib/redux/store";

import { Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({ weight: "300", subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
    kart: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.className} mainPage fixed`}>
                <Header />
                <Provider store={store}>
                    <Alert />
                    {children}
                    <Kart />
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
