export const wcMAP = {
    brands: {
        KEEPHONE: 23,
        PITAKA: 41,
    },
    categories: {
        "Camera Protector": 47,
        "Case Wallet": 78,
        Charger: 55,
        "Charging Cable": 57,
        Earbuds: 21,
        "Frame Case": 44,
        "Headphones Case": 50,
        "Laptop Case": 49,
        Magnetic: 58,
        Magsafe: 18,
        "Phone Case": 17,
        "Power Bank": 95,
        Privacy: 53,
        "Screen Protector": 52,
        "SmartWatch Case": 51,
        "Stand Case": 77,
        "Stand Power Bank": 98,
        "Tablet Case": 48,
        "Type-C": 97,
        Uncategorized: 15,
        Wallet: 36,
        Wireless: 20,
        "Wireless Power Bank": 96,
        "With Cable": 56,
    },
    attributes: {
        Capacity: {
            self: 5,
            options: {
                "10000mAh": 103,
                "1200mAh": 102,
                "20000mAh": 104,
                "5000mAh": 101,
            },
        },
        Color: {
            self: 1,
            options: {
                Black: 31,
                Blue: 32,
                Bronze: 87,
                Brown: 33,
                Clear: 22,
                Desert: 37,
                Deset: 90,
                Gray: 34,
                Green: 60,
                Gunmetal: 99,
                "Light Blue": 62,
                "Light Green": 63,
                "Light Yellow": 64,
                Multicolor: 81,
                "NO.1": 91,
                "NO.2": 92,
                "NO.3": 93,
                "NO.9": 94,
                Orange: 100,
                Pink: 65,
                Purple: 61,
                "Semi Clear Black": 82,
                "Semi Clear Desert": 83,
                "Semi Clear Titan": 84,
                Silver: 45,
                Subset: 80,
                Sunset: 89,
                Titan: 59,
                "Titanium Gray": 43,
                White: 40,
            },
        },
        "For Device": {
            self: 4,
            options: {
                "IP 13": 67,
                "IP 13 Pro": 68,
                "IP 13 Pro Max": 69,
                "IP 14": 70,
                "IP 14 Plus": 71,
                "IP 14 Pro": 72,
                "IP 14 Pro Max": 73,
                "IP 15": 74,
                "IP 15 Pro": 75,
                "IP 15 Pro Max": 76,
                "IP 16": 85,
                "IP 16 PLUS": 86,
                "IP 16 Pro": 38,
                "IP 16 Pro Max": 39,
                IP16: 88,
                "SAM S24": 29,
                "SAM S24 Plus": 30,
                "SAM S24 Ultra": 28,
                "SAM S25": 24,
                "SAM S25 Plus": 25,
                "SAM S25 Ultra": 26,
            },
        },
        Material: {
            self: 2,
            options: {
                Carbon: 42,
                Glass: 66,
                Leather: 35,
                Silicon: 27,
            },
        },
    },
} as const;
