export const wcMAP = {
    brands: {
        KEEPHONE: 23,
        PITAKA: 41,
    },
    categories: {
        "Camera Protector": 47,
        Charger: 55,
        "Charging Cable": 57,
        Earbuds: 21,
        "Frame Case": 44,
        "Headphones Case": 50,
        "Laptop Case": 49,
        Magnetic: 58,
        Magsafe: 18,
        "Phone Case": 17,
    },
    attributes: {
        Color: {
            self: 1,
            options: {
                Black: 31,
                Blue: 32,
                Brown: 33,
                Clear: 22,
                Desert: 37,
                Gray: 34,
                Green: 60,
                "Light Blue": 62,
                "Light Green": 63,
                "Light Yellow": 64,
                Pink: 65,
                Purple: 61,
                Silver: 45,
                Titan: 59,
                "Titanium Gray": 43,
                White: 40,
            },
        },
        "For Device": {
            self: 4,
            options: {
                "IP 13": 67,
                "IP 13 Pro": 68,
                "IP 13 Pro Max": 69,
                "IP 14": 70,
                "IP 14 Plus": 71,
                "IP 14 Pro": 72,
                "IP 14 Pro Max": 73,
                "IP 15": 74,
                "IP 15 Pro": 75,
                "IP 15 Pro Max": 76,
                "IP 16 Pro": 38,
                "IP 16 Pro Max": 39,
                "SAM S24": 29,
                "SAM S24 Plus": 30,
                "SAM S24 Ultra": 28,
                "SAM S25": 24,
                "SAM S25 Plus": 25,
                "SAM S25 Ultra": 26,
            },
        },
        Material: {
            self: 2,
            options: {
                Carbon: 42,
                Glass: 66,
                Leather: 35,
                Silicon: 27,
            },
        },
    },
} as const;
